project_id = "tech-summit2022"
project = "tech-summit2022"
dataset_id = "test_dataset"
source_table = "test_table"
target_table = "scheduled_table"
sql_file = "dev_scheduled_query.sql"
schedule = "every 15 minutes"
