steps:
- id: 'BigQuery dry-run - Dev'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - ENV=dev make validate-sql

- id: 'Terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - apk add --update make && ENV=dev make plan
